=== YaroslavLichnyi/informationSystem/server_data/rules.dtd
<!ELEMENT restaurant (dish*)>
<!ELEMENT dish (description+)>
<!ATTLIST dish
        name CDATA #REQUIRED
        price CDATA #REQUIRED
>
<!ELEMENT description (#PCDATA)>

=== YaroslavLichnyi/informationSystem/server_data/restaurant.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE restaurant SYSTEM "rules.dtd">
<restaurant>
    <dish-category id="1" name="Meat" healthy-food="false">
        <dish id="1" name="Pork" price="150.0" dish-category-id="1">
            <description>Steak</description>
        </dish>
        <dish id="2" name="Beaf" price="200.0" dish-category-id="1">
            <description>Beafsteak</description>
        </dish>
        <dish id="3" name="Chicken" price="100.0" dish-category-id="1">
            <description>Roast chicken</description>
        </dish>
        <dish id="4" name="Crab" price="250.0" dish-category-id="1">
            <description>Boiled Crab</description>
        </dish>
    </dish-category>
    <dish-category id="2" name="Garnishes" healthy-food="false">
        <dish id="5" name="Potato" price="35.0" dish-category-id="2">
            <description>Baked potato</description>
        </dish>
        <dish id="6" name="Buckwheat" price="20.0" dish-category-id="2">
            <description>Boiled buckwheat</description>
        </dish>
        <dish id="7" name="Pasta" price="25.0" dish-category-id="2">
            <description>Pasta with cheese</description>
        </dish>
        <dish id="8" name="Rice" price="30.0" dish-category-id="2">
            <description>Boiled rice</description>
        </dish>
    </dish-category>
    <dish-category id="3" name="Salads" healthy-food="false">
        <dish id="9" name="Cabbage" price="25.0" dish-category-id="3">
            <description>Sliced cabbage</description>
        </dish>
        <dish id="10" name="Fresh vegetables" price="50.0" dish-category-id="3">
            <description>Fresh sliced vegetables</description>
        </dish>
    </dish-category>
    <dish-category id="4" name="Desserts" healthy-food="true">
        <dish id="11" name="Cake" price="55.0" dish-category-id="4">
            <description>Cherry cake</description>
        </dish>
        <dish id="12" name="Ice Cream" price="45.0" dish-category-id="4">
            <description>Strawberry ice cream</description>
        </dish>
        <dish id="13" name="Chocolate" price="50.0" dish-category-id="4">
            <description>Hot chocolate</description>
        </dish>
    </dish-category>
    <dish-category id="5" name="Drinks" healthy-food="false">
        <dish id="14" name="Coffee" price="60.0" dish-category-id="5">
            <description>Pure black coffee</description>
        </dish>
        <dish id="15" name="Juice" price="20.0" dish-category-id="5">
            <description>Fruit juice</description>
        </dish>
        <dish id="16" name="Water" price="10.0" dish-category-id="5">
            <description>Drink water</description>
        </dish>
        <dish id="17" name="Cola" price="25.0" dish-category-id="5">
            <description>Coca cola</description>
        </dish>
        <dish id="18" name="Milk" price="15.0" dish-category-id="5">
            <description>Pure milk</description>
        </dish>
    </dish-category>
</restaurant>
